ecommerce_homepage:
    path:     /
    defaults: { _controller: EcommerceBundle:Default:index }
ecommerce_contactpage:
    path:     /contact
    defaults: { _controller: EcommerceBundle:Default:pagecontact }
ecommerce_produitpage:
    path:     /produit
    defaults: { _controller: EcommerceBundle:Default:pageproduit }
ecommerce_ajoutepage:
    path:     /ajoute
    defaults: { _controller: EcommerceBundle:Default:pageajoute }
ecommerce_voirepage:
    path:     /{id}/voir
    defaults: { _controller: EcommerceBundle:Default:pagevoir }
    requirements:
       id: \d+
ecommerce_editerpage:
    path:     /{id}/editer
    defaults: { _controller: EcommerceBundle:Default:pageediter }
    requirements:
       id: \d+
ecommerce_supprimerpage:
    path:     /{id}/supprimer
    defaults: { _controller: EcommerceBundle:Default:pagesupprimer }
    requirements:
       id: \d+
