ecommerce_homepage:
    path:     /
    defaults: { _controller: EcommerceBundle:Default:index }
ecommerce_contactpage:
    path:     /contact
    defaults: { _controller: EcommerceBundle:Default:pagecontact }
ecommerce_produitpage:
    path:     /produit
    defaults: { _controller: EcommerceBundle:Default:pageproduit }
ecommerce_ajoutepage:
    path:     /ajoute
    defaults: { _controller: EcommerceBundle:Default:pageajoute }
ecommerce_voirepage:
    path:     /voir/{id}
    defaults: { _controller: EcommerceBundle:Default:pagevoir }
    requirements:
       id: \d+
ecommerce_editerpage:
    path:     /editer/{id}
    defaults: { _controller: EcommerceBundle:Default:pageediter }
    requirements:
       id: \d+
ecommerce_supprimerpage:
    path:     /supprimer/{id}
    defaults: { _controller: EcommerceBundle:Default:pagesupprimer }
    requirements:
       id: \d+
ecommerce_categoriepage:
    path:     /categorie
    defaults: { _controller: EcommerceBundle:Default:pagecategorie }
ecommerce_recherchepage:
    path:     /recherche
    defaults: { _controller: EcommerceBundle:Recherche:pagerecherche }
ecommerce_recherche:
    path:     /recherchee
    defaults: { _controller: EcommerceBundle:Recherche:Recherche2 }

ajouterpanier:
    path:     /ajouterpanier/{id}
    defaults: { _controller: EcommerceBundle:Panier:ajouterpanier }
    requirements:
       id: \d+
supprimerpanier:
    path:     /supprimerpanier/{id}
    defaults: { _controller: EcommerceBundle:Panier:supprimerpanier }
    requirements:
       id: \d+
panier:
    path:     /panier
    defaults: { _controller: EcommerceBundle:Panier:panier }
validation:
    path:     /validation
    defaults: { _controller: EcommerceBundle:Validation:validation }
