<?php

namespace Ecommerce\EcommerceBundle\Entity;

/**
 * articleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class articleRepository extends \Doctrine\ORM\EntityRepository
{

public function findProduiteBynom($motclee){

  $query= $this->createQueryBuilder('p')
  ->where('p.nom like :nom ')
  ->setParameter('nom',$motclee.'%')
  ->orderBy('p.nom','ASC')
  ->getQuery();
  return $query->getResult();
}

public function findArray($array){

  $query= $this->createQueryBuilder('p')
  ->Select('p')
  ->where('p.id IN (:array) ')
  ->setParameter('array',$array);
  return $query->getQuery()->getResult();
}

}
