<?php

namespace Ecommerce\EcommerceBundle\Repository;

/**
 * articleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduiteRepository extends \Doctrine\ORM\EntityRepository
{

public function recherche($chaine){

$qb = $this->createQueryBuilder('u')
->select('u')
->where('u.nom = chaine')
->setParameter('chaine',$chaine);
return $qb->getQuery()->getResult();
}



}
